# Site settings
title: Rodrigo Roim
name: Rodrigo Roim
email: rodrigo@rro.im
description: > # this means to ignore newlines until "baseurl:"
  Computer engineering student from Brazil.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rro.im" # the base hostname & protocol for your site
github_username:  roim
linkedin_username: rodrigoroim
stackoverflow_username: roim

# Build settings
markdown: kramdown
