# Site settings
title: Rodrigo Roim
name: Rodrigo Roim
email: roim.rodrigo@gmail.com
description: >
  Software Engineer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://roim.github.io" # the base hostname & protocol for your site

# Blog settings
permalink: /:title

# Usernames
github_username: roim
linkedin_link: https://www.linkedin.com/in/rodrigoroim
stackoverflow_link: http://stackoverflow.com/users/938782/roim

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]

# Carte Noire
disqus_account: rroim
github_repository: https://github.com/roim/roim.github.io
post_limit: 5
footer_left: "Copyright (C) Rodrigo Roim Ferreira"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/roim/roim.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"
