# Site settings
title: Rodrigo Roim
title_image: "http://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
name: Rodrigo Roim
email: rodrigo@rro.im
description: >
  Computer engineering student from Brazil.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rro.im" # the base hostname & protocol for your site

# Blog settings
permalink: /:title

# Usernames
github_username: roim
linkedin_link: https://br.linkedin.com/in/rodrigoroim
stackoverflow_link: http://stackoverflow.com/users/938782/roim

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]

# Carte Noire
disqus_account: rroim
github_repository: https://github.com/roim/roim.github.io
post_limit: 5
footer_left: "Copyright (C) 2015 - Rodrigo Roim Ferreira"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/roim/roim.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"
